---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: verticalautoscalers.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: verticalautoscalers
    singular: verticalautoscaler
    kind: VerticalAutoscaler
    shortNames:
      - vpa
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          required:
            - selector
          properties:
            selector:
              type: object
            updatePolicy:
              type: object
              properties:
                updateMode:
                  type: string
            resourcePolicy:
              type: object
              properties:
                containerPolicies:
                  type: array
                  items:
                    type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: verticalautoscalercheckpoints.autoscaling.k8s.io
spec:
  group: autoscaling.k8s.io
  version: v1beta1
  scope: Namespaced
  names:
    plural: verticalautoscalercheckpoints
    singular: verticalautoscalercheckpoint
    kind: VerticalAutoscalerCheckpoint
    shortNames:
      - vpacheckpoint
